spring.application.name=FuzzyCalculator

spring.datasource.url=jdbc:postgresql://localhost:5432/fuzzy_db
spring.datasource.username=myuser
spring.datasource.password=mypassword

# Spring Data JPA ?????????
# update ????????, ??? Spring ??? ??????? ??????? ? ?? ?? ?????? ????? Java-???????!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false